services:
  Shared.Logger:
    class: ../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  TicketsManagment.Shared.PostgreConfig:
    factory:
      class: ../../../../Contexts/TicketsManagment/Shared/infrastructure/persistence/postgre/TypeOrmConfigFactory
      method: 'createConfig'

  TicketsManagment.Shared.ConnectionManager:
    factory:
      class: ../../../../Contexts/Shared/infrastructure/persistence/typeorm/TypeOrmClientFactory
      method: 'createClient'
    arguments: ['TicketsManagment', '@TicketsManagment.Shared.PostgreConfig']

  TicketsManagment.Shared.CommandHandlers:
    class: ../../../../Contexts/Shared/infrastructure/CommandBus/CommandHandlers
    arguments: ['!tagged commandHandler']

  TicketsManagment.Shared.domain.CommandBus:
    class: ../../../../Contexts/Shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@TicketsManagment.Shared.CommandHandlers']

  TicketsManagment.Shared.QueryHandlers:
    class: ../../../../Contexts/Shared/infrastructure/QueryBus/QueryHandlers
    arguments: ['!tagged queryHandler']

  TicketsManagment.Shared.domain.QueryBus:
    class: ../../../../Contexts/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@TicketsManagment.Shared.QueryHandlers']

  #Configuracion de RabbitMQ

  TicketsManagment.Shared.domain.EventBus:
    factory:
      class: ../../../../Contexts/TicketsManagment/Shared/infrastructure/RabbitMQ/RabbitMQEventBusFactory
      method: 'create'
    arguments: ['@TicketsManagment.Shared.RabbitMQConnection', '@TicketsManagment.Shared.RabbitMQQueueFormatter', '@TicketsManagment.Shared.RabbitMQConfig']

  TicketsManagment.Shared.RabbitMQConfig:
    factory:
      class: ../../../../Contexts/TicketsManagment/Shared/infrastructure/RabbitMQ/RabbitMQConfigFactory
      method: 'createConfig'

  TicketsManagment.Shared.RabbitMQQueueFormatter:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['TicketsManagment']

  TicketsManagment.Shared.RabbitMQConnection:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMqConnection
    arguments: ['@TicketsManagment.Shared.RabbitMQConfig']

  TicketsManagment.Shared.RabbitMQConfigurer:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQConfigurer
    arguments: ['@TicketsManagment.Shared.RabbitMQConnection', '@TicketsManagment.Shared.RabbitMQQueueFormatter']
