services:
  Apps.EventManagment.controllers.EventPutController:
    class: ../../controllers/EventPutController
    arguments: ['@EventManagment.Shared.domain.CommandBus']

  # Apps.mooc.controllers.CoursesCounterGetController:
  #   class: ../../controllers/CoursesCounterGetController
  #   arguments: ['@Mooc.Shared.domain.QueryBus']
