services:
  UserManagment.Users.domain.UserRepository:
    class: ../../../../Contexts/UserManagment/Users/infrastructure/persistence/PostgresUserRepository
    arguments: ['@UserManagment.Shared.ConnectionManager']

  UserManagment.Users.application.UserCreator:
    class: ../../../../Contexts/UserManagment/Users/application/Create/UserCreator
    arguments: ['@UserManagment.Users.domain.UserRepository', '@UserManagment.Shared.domain.EventBus']

  UserManagment.users.CreateUserCommandHandler:
    class: ../../../../Contexts/UserManagment/Users/application/Create/CreateUserCommandHandler
    arguments: ['@UserManagment.Users.application.UserCreator']
    tags:
      - { name: 'commandHandler' }

  UserManagment.users.CreateUser:
    class: ../../../../Contexts/UserManagment/Users/application/Create/CreatorUserDomainEvent
    arguments: ['@UserManagment.Users.domain.UserRepository', '@UserManagment.Shared.domain.EventBus']

  UserManagment.users.CreatedUserOnUserCreated:
    class: ../../../../Contexts/UserManagment/Users/application/Create/CreateUserOnUserCreated
    arguments: ['@UserManagment.users.CreateUser']
    tags:
      - { name: 'domainEventSubscriber' }
