services:
  UserManagment.Users.domain.UserRepository:
    class: ../../../../Contexts/UserManagment/Users/infrastructure/persistence/PostgresUserRepository
    arguments: ['@UserManagment.Shared.ConnectionManager']

  UserManagment.Users.application.UserCreator:
    class: ../../../../Contexts/UserManagment/Users/application/Create/UserCreator
    arguments: ['@UserManagment.Users.domain.UserRepository']

  UserManagment.users.CreateUserCommandHandler:
    class: ../../../../Contexts/UserManagment/Users/application/Create/CreateUserCommandHandler
    arguments: ['@UserManagment.Users.application.UserCreator']
    tags:
      - { name: 'commandHandler' }
