services:
  EventManagment.Lots.domain.EventRepository:
    class: ../../../../Contexts/EventManagment/Lots/infrastructure/persistence/MySQLLotRepository
    arguments: ['@EventManagment.Shared.ConnectionManager']

  EventManagment.Lots.application.LotCreator:
    class: ../../../../Contexts/EventManagment/Lots/application/Create/LotCreator
    arguments: ['@EventManagment.Events.domain.EventRepository', '@EventManagment.Shared.domain.EventBus']

  EventManagment.Lots.CreateEventCommandHandler:
    class: ../../../../Contexts/EventManagment/Lots/application/Create/CreateEventCommandHandler
    arguments: ['@EventManagment.Lots.application.LotCreator']
    tags:
      - { name: 'commandHandler' }
